# Generated by Django 5.2.9 on 2025-12-20 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_add_job_requirements_and_application_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(max_length=50)),
                ('name_with_type', models.CharField(max_length=150)),
                ('path', models.CharField(blank=True, max_length=200, null=True)),
                ('path_with_type', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quận/Huyện',
                'verbose_name_plural': 'Quận/Huyện',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(max_length=50)),
                ('name_with_type', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tỉnh/Thành phố',
                'verbose_name_plural': 'Tỉnh/Thành phố',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='job',
            name='city',
        ),
        migrations.AddField(
            model_name='job',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.district'),
        ),
        migrations.AddField(
            model_name='district',
            name='parent_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='jobs.province'),
        ),
        migrations.AddField(
            model_name='job',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.province'),
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(max_length=50)),
                ('name_with_type', models.CharField(max_length=150)),
                ('path', models.CharField(blank=True, max_length=300, null=True)),
                ('path_with_type', models.CharField(blank=True, max_length=400, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='jobs.district')),
            ],
            options={
                'verbose_name': 'Xã/Phường',
                'verbose_name_plural': 'Xã/Phường',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.ward'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
