# Generated by Django 5.2.9 on 2025-12-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_district_province_remove_job_city_job_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='address_detail',
            field=models.CharField(blank=True, help_text='Số nhà, tên đường, tòa nhà...', max_length=255, null=True),
        ),
    ]
