# Generated by Django 5.2.9 on 2025-12-21 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_address_detail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_file', models.FileField(upload_to='user_cvs/')),
                ('file_type', models.CharField(blank=True, max_length=10)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('extracted_text_cleaned', models.TextField(blank=True, null=True)),
                ('detected_language', models.CharField(blank=True, default='vi', max_length=10)),
                ('is_processed', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='user_cvs', to='jobs.jobcategory')),
                ('skills', models.ManyToManyField(blank=True, related_name='user_cvs', to='jobs.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cvs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User CV',
                'verbose_name_plural': 'User CVs',
                'ordering': ['-created_at'],
            },
        ),
    ]
