# Generated by Django 5.2.9 on 2025-12-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_usercv'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercv',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercv',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Đang chờ xử lý'), ('processing', 'Đang xử lý OCR'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại'), ('no_tesseract', 'Chưa cài Tesseract OCR'), ('no_text', 'Không trích xuất được text')], default='pending', max_length=20),
        ),
    ]
