# Generated by Django 5.2.9 on 2025-12-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_userskillprofile_delete_usercv'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_size',
            field=models.CharField(blank=True, help_text='Ví dụ: 25-99 nhân viên', max_length=50, null=True),
        ),
    ]
